version: 2.1
orbs:
  ruby: circleci/ruby@1.0 

jobs:
  test:
    docker:
      - image: cimg/ruby:2.7.1
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test

workflows:
  version: 1
  test:
    jobs:
      - test
