version: 2.1
orbs:
  ruby: circleci/ruby@1.0 

jobs:
  test:
    docker:
      - image: cimg/ruby:2.7.1
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
  deploy:
    docker:
      - image: circleci/ruby:2.7-node-browsers
    
    working_directory: ~/detran_faker

    steps:
      - checkout
      - run:
          name: Setup Rubygems
          command: bash .circleci;setup-rubygems.sh

      - run:
          name: Publish to Rubygems
          command: |
            gem build detran_faker.gemspec
            gem push "detran_faker-$(git describe --tags).gem"

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
